### ISSUE TITLE
Setting new dimmer values doesn't work (bounces back to old value)

### ISSUE THREAD

**Issue by hubert3** [jmichas/homebridge-zway-plugin#5]
I have a Z-Wave dimmer device added in Z-Way (set to type Lightbulb in Apple Home)

When I want to change the brightness from 50% to (for example) 99%, the Home UI and dimmer briefly reflect the new brightness value, but it then jumps back to the original value of 50%

After some debugging, it seems that homebridge-zway-plugin is sending two HTTP requests to Z-Way in quick succession in this order:

1) An "exact" request that sets the new dimmer level
2) An "on" request that turns the device on

Z-Way sends a Z-Wave command to the device setting the new requested dimmer level immediately after receiving HTTP request 1, but request 2 which is received immediately afterwards makes it send another Z-Wave command containing the old dimmer value (this could possibly be considered a bug in Z-Way due to some kind of race condition...)

It seems like this is happening because the accessory has both 'On' and 'Brightness' characteristics, so the plugin is sending requests for both attributes to Z-Way

For my accessory, the 2nd request seems unnecessary, and I've modified my local copy of the plugin to not send the "on" request to this particular device, which fixes the issue

Looking on the Z-Way forum it seems that other people are also experiencing this, so I wonder if a more general fix could be to change the order of the requests so that 'on' is sent first and 'exact' is sent 2nd?

```
Mon, 29 May 2023 12:06:10 GMT ZWayServer Sending zwayRequest ZWayVDev_zway_5-0-38 exact {"level":56}
Mon, 29 May 2023 12:06:10 GMT ZWayServer Sending zwayRequest ZWayVDev_zway_5-0-38 on undefined
Mon, 29 May 2023 12:06:10 GMT ZWayServer Device Corner Lamp, characteristic On changed from true to true
Mon, 29 May 2023 12:06:13 GMT ZWayServer Got 2 updates.
Mon, 29 May 2023 12:06:13 GMT ZWayServer Characteristic Name on Corner Lamp showed timestamp update without value change.
Mon, 29 May 2023 12:06:13 GMT ZWayServer Characteristic On on Corner Lamp showed timestamp update without value change.
Mon, 29 May 2023 12:06:13 GMT ZWayServer Updated characteristic Brightness on Corner Lamp
Mon, 29 May 2023 12:06:18 GMT ZWayServer Got 3 updates.
```

**Comment by hubert3** [comment]
I have confirmed that the "on" zwayRequest without a level which is sent immediately following the "exact" request with the new dimmer level is the cause of the issue and makes Z-Way immediately revert to the previous dimmer value

I haven't figured out yet why the plug-in code is sending these 2 requests in quick succession but adding some debug code which simply omits the "on" request fixes the issue

**Comment by jmichas** [comment]
Thanks for the info. This is great. I also have this problem but I was looking at it from the other end. I thought maybe something in z-way changed in a firmware update. Also, I have Leviton dimmers exclusively so I thought maybe it was something specific to them as this used to work perfectly and seemed to suddenly stop.

I will look into reversing the order of events and see if that will fix it, either that or delay the second call so it doesn't get ignored by zway.

**Comment by jmichas** [comment]
@hubert3 Also, sorry, it appears I did not get notified when you posted your issues.

**Comment by hubert3** [comment]
No problem. The hacky fix I made in my local copy just skips sending the 'on' request to Z-Way entirely for one of my lamps where the issue is really noticeable, so it only ever sends the 'exact' request containing a brightness level.

Not sure if there are other dimmer devices out there where the 'on' request is needed but it isn't on mine

```
diff --git a/index.js b/index.js
index 73dd035..5cf7cf6 100644
--- a/index.js
+++ b/index.js
@@ -149,8 +149,15 @@ ZWayServerPlatform.prototype = {
         opts.headers = {
             "Cookie": "ZWAYSession=" + this.sessionId
         };
-
-        request(opts, function(error, response, body){
+        debug("zwayRequest called with opts "+JSON.stringify(opts));
+        if (opts.url == 'http://127.0.0.1:8083/ZAutomation/api/v1/devices/ZWayVDev_zway_5-0-38/command/on')
+        {
+            debug("Ignoring ZWayVDev_zway_5-0-38/command/on");
+            deferred.resolve();
+        }
+        else
+        {
+            request(opts, function(error, response, body){
             if(response && response.statusCode == 401){
                 debug("Authenticating...");
                 request({
@@ -199,7 +206,7 @@ ZWayServerPlatform.prototype = {
                 if(response) debug(response); else debug(error);
                 deferred.reject(response);
             }
-        });
+        });}
         return deferred.promise;
```

**Comment by jmichas** [comment]
Cool, thanks. Yeah this is a huge problem for me. I am looking into what options there are to fix it more generally.
Are the "Sending zwayRequest ..." lines in your log extra debugging code that you added?

**Comment by hubert3** [comment]
> Cool, thanks. Yeah this is a huge problem for me. I am looking into what options there are to fix it more generally.
> Are the "Sending zwayRequest ..." lines in your log extra debugging code that you added?

yes, see the line

```debug("zwayRequest called with opts "+JSON.stringify(opts));```

in the diff

**Comment by jmichas** [comment]
This should be fixed in v1.0.3.
I put in some code for the On handler so that if the vdev.metrics.level is zero then the On http call will be fired. If the level is >0 then we assume that the dimmer is already "on". There isn't a property for on/off and from what I can tell level is always zero when a dimmer is off.

**Comment by hubert3** [comment]
Confirm v1.0.3 works fine with my dimmer lamp (brightness level does not jump around) and I don't need my custom fix any more, nice work

**Comment by jmichas** [comment]
@hubert3 Cool, thanks for reporting and testing 👍
