### ISSUE TITLE
Z-Way authentication error handling

### ISSUE THREAD

**Issue by hubert3** [jmichas/homebridge-zway-plugin#6]
The cookies obtained for the Z-Way API seem to expire at some point resulting in 401 errors in the Homebridge log

This should trigger a new login to obtain a new cookie, but this doesn't seem to happen reliably

Will post more debug info when I can get it

**Comment by jmichas** [comment]
@hubert3 So is this the message that says it can't reach the zway server, check your credentials or something like that?
If it is, that has been a long standing error in all the versions of zway plugin out there. 

The way I handled it was to set cron job on my raspberry pi to reboot at 3am every night. It seems that error is some sort of memory leak I think.

But whatever other debug info you can collect I will try and fix. I haven't gotten any errors since I fixed the last minor bug, but i reboot every day.

**Comment by hubert3** [comment]
Yes that's the error in the homebridge log

When it happens I think you can still log in to Z-Way web interface manually so I'm not sure it's a z-way memory leak or just a bug in the plugin not performing the re-login correctly?

Rebooting the raspberry pi daily seems a bit inelegant.

If it is confirmed as a Z-Way memory leak maybe the plugin could restart the Z-Way service (assuming they're running on the same system) so Homebridge keeps running. We should also report the bug to Z-Way if it is really on their side

**Comment by jmichas** [comment]
Yeah I agree on the solution being a bit brute force, but when I was only using the original plugin this was the only work around. I think it is more of a homebridge memory problem. What I was hoping was that after refactoring the code into the typescript plugin template that homebridge supplies, the problem would go away. At least then I would be more familiar with the code and able to diagnose it easier.

Do you have any debug info on it? If it is a cookie thing that sort of makes sense. There is a reference to tough cookie in the code but as I started to refactor everything, it appears the cookie is not being set, or maybe not being set from all the places it should be. So maybe it isn't memory related at all, that was just the explanation given in the initial issue ages ago in the original plugin. 

I will look over the auth code and see if it isn't a simple logic error in handling 401 errors when the cookie expires.

**Comment by hubert3** [comment]
I guess a simple test would be to restart Homebridge but not Z-Way when this error happens - If login works, the issue is on the homebridge/plugin side and not Z-Way

**Comment by hubert3** [comment]
In the Z-Way admin interface check out User Management on this page http://rpi/8083/smarthome/#/admin

Edit the account the plugin is using to login, it shows active sessions (which I assume corresponds to cookies)

It seems the default expiry is 1 week but you can also make it permanent / infinite

You can also kill a particular session there which could be useful for testing the re-login functionality

**Comment by hubert3** [comment]
As soon as I kill the most recent session in Z-Way, I get this in the Homebridge log every 5 seconds:

[21/07/2023, 10:04:31] [ZWayServer] ERROR: Fatal! Authentication failed (error code 401)! Check the username and password in config.json!
Fri, 21 Jul 2023 00:04:36 GMT ZWayServer Authenticating...
[21/07/2023, 10:04:36] [ZWayServer] ERROR: Fatal! Authentication failed (error code 401)! Check the username and password in config.json!
Fri, 21 Jul 2023 00:04:41 GMT ZWayServer Authenticating...
[21/07/2023, 10:04:41] [ZWayServer] ERROR: Fatal! Authentication failed (error code 401)! Check the username and password in config.json!
Fri, 21 Jul 2023 00:04:46 GMT ZWayServer Authenticating...

There is no new session appearing in the Z-Way interface.

If I restart Homebridge (without restarting Z-Way) the plugin logs in fine.

So it seems the 401 handling / re-login code in the plugin is actually broken and it's not Z-Way causing this.

**Comment by hubert3** [comment]
The way the plugin deals with cookies seems a bit screwy

It enables the requests 'jar' cookie jar option but also manually sets a HTTP header to send the session cookie:

```
        opts.headers = {
            "Cookie": "ZWAYSession=" + this.sessionId
        };
```

The re-authentication failure seems to be caused by the login POST request after receiving a 401 still including the stale cookie header. The successful initial login POST doesn't include a cookie header.

Disabling the jar option when the login POST request is constructed seems to fix the issue. This should ensure a cookie is never sent on the login POST request which is the correct behaviour.

https://github.com/jmichas/homebridge-zway-plugin/pull/7

**Comment by jmichas** [comment]
Yeah I noticed that too when I was converting to typescript, but since I always restart my pi everyday and never get the reauth error, I didn't really think much of it. I will check out your pull request, thanks for helping out!

**Comment by jmichas** [comment]
Hey, how can we expire the cookie manually, do you know? I wrote tests for the login/auth request stuff in my new branch in typescript but I don't have a test that reauths when the cookie is expired. It would be nice to do one so we don't introduce this bug in the new code base when its done.

**Comment by hubert3** [comment]
> Hey, how can we expire the cookie manually

See one of my comments above, you can manually kill particular active sessions in the Z-Way admin gui

**Comment by jmichas** [comment]
Yeah I was looking for an automated way to do it for integration tests. I will look at the zway docs, they may have an endpoint that can be hit to do it.

**Comment by hubert3** [comment]
> Yeah I noticed that too when I was converting to typescript, but since I always restart my pi everyday and never get the reauth error, I didn't really think much of it. I will check out your pull request, thanks for helping out!

For what it's worth, I stopped doing daily reboots of my RPi via crontab a while ago since the re-auth fix in https://github.com/jmichas/homebridge-zway-plugin/pull/7 and now have uptimes of several weeks of both the Z-Way server process (v4.1.1) and Homebridge running with no issues and no apparent memory leaks.

**Comment by jmichas** [comment]
@hubert3 Yeah, I stopped running my daily reboot as well and everything seems fine. Maybe the original thread I read about a memory leak was not accurate. Nice work on catching the real bug and supplying a fix!
